module.exports = [
  { domain: 'seed.defcoin.io', type: 'seed', priority: 10, source: 'DefCoinCore v2.0.0 chainparams.cpp' },
  { domain: 'seed2.defcoin.io', type: 'seed', priority: 11, source: 'DefCoinCore v2.0.0 chainparams.cpp' },
  { domain: 'defcoin.io', type: 'site', priority: 20, source: 'Defcoin history' },
  { domain: 'seed.defcoin-ng.org', type: 'seed', priority: 30, source: 'Defcoin-ng history' },
  { domain: 'seed2.defcoin-ng.org', type: 'seed', priority: 31, source: 'Defcoin-ng history' },
  { domain: 'defcoin.mikej.tech', type: 'seed', priority: 40, source: 'Defcoin community seed' },
  { domain: 'seed.defcoin.mikej.tech', type: 'seed', priority: 50, source: 'Defcoin community seed aggregator' },
  { domain: 'defcoin.dc903.org', type: 'current', priority: 60, source: 'Current DC903 service' },
  { domain: 'pool.acor.to', type: 'pool', priority: 100, source: 'defcoinstats pool list' },
  { domain: 'defcoin-pool.subba.net', type: 'pool', priority: 101, source: 'defcoinstats pool list' },
  { domain: 'www.redbaron.us', type: 'pool', priority: 102, source: 'defcoinstats pool list' },
  { domain: 'redbaron.us', type: 'pool', priority: 103, source: 'defcoinstats pool list' },
  { domain: 'chunkypools.com', type: 'pool', priority: 104, source: 'defcoinstats pool list' },
  { domain: 'defcoin.us', type: 'pool', priority: 105, source: 'defcoinstats pool list' },
  { domain: 'coin.iptron.net', port: '13370', type: 'pool', priority: 106, source: 'defcoinstats pool list' },
  { domain: 'cryptoheater.com', type: 'pool', priority: 107, source: 'defcoinstats pool list' },
  { domain: 'www.defcoinpool.com', type: 'pool', priority: 108, source: 'defcoinstats pool list' },
  { domain: 'defcoinpool.com', type: 'pool', priority: 109, source: 'defcoinstats pool list' },
  { domain: 'defcoin.host', staticIps: ['135.148.43.189'], type: 'pool', priority: 110, source: 'defcoinstats pool list and historical host IP note' },
  { domain: 'defcoin.dc801.org', type: 'historic-pool', priority: 120, source: 'historical Defcoin pool list' },
  { domain: 'unknownminingpool.com', type: 'historic-pool', priority: 121, source: 'historical Defcoin pool list' },
  { domain: 'mine.laiw.com', type: 'historic-pool', priority: 122, source: 'historical Defcoin pool list' },
  { domain: 'explorer.def-coin.org', type: 'historic-explorer', priority: 130, source: 'historical Defcoin explorer tool site' }
];
